theme = "hyde"
baseURL = 'https://agroprocess.github.io'
languageCode = 'pt-br'
title = 'Agroprocess'

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/dakoctba/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/dakoctba/"}
  ]

[params]
  themeColor = "theme-base-0b"
